import {  Montserrat, Poppins } from "next/font/google";
import "./globals.css";




const popins=Poppins({
  variable: "--font-poppins",
  subsets:["latin"],
  weight:["400","600","800"]

})

export const moneSerrat=Montserrat({
  variable: "--font-montserrat",
  subsets:["latin"],
  weight:["400","600","800"]
})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`${popins.className} min-h-full flex flex-col`}>
       
       
        {children}
        </body>
    </html>
  );
}
